name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Copy JAR to EC2
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          source: target/todolist-0.0.1-SNAPSHOT.jar
          target: /home/ubuntu

      - name: Start app on EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          script: |
            pkill -f 'todolist-0.0.1-SNAPSHOT.jar' || true
            cd /home/ubuntu
            set -a
            source .env
            set +a
            nohup java -jar todolist-0.0.1-SNAPSHOT.jar > app.log 2>&1 &
