name: Deploy to EC2

on:
  push:
    branches:
      - main  # Cambia si usas otra rama

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar Java 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Compilar con Maven
        run: mvn clean package -DskipTests

      - name: Copiar .jar a EC2
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "target/todolist-0.0.1-SNAPSHOT.jar"
          target: "/home/ubuntu"

      - name: Ejecutar .jar en EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            pkill -f 'todolist-0.0.1-SNAPSHOT.jar' || true
            nohup java -jar /home/ubuntu/todolist-0.0.1-SNAPSHOT.jar > app.log 2>&1 &
